add_subdirectory(button)
add_subdirectory(icon-button)
add_subdirectory(fab)
add_subdirectory(checkbox)
add_subdirectory(switch)
add_subdirectory(radio-button)
add_subdirectory(slider)
add_subdirectory(segmented-button)
add_subdirectory(linear-progress-indicator)
add_subdirectory(circular-progress-indicator)
add_subdirectory(card)
add_subdirectory(label)
add_subdirectory(divider)
add_subdirectory(chip)
add_subdirectory(badge)
add_subdirectory(app-bar)
add_subdirectory(tab-bar)
add_subdirectory(dialog)
add_subdirectory(menu)
add_subdirectory(bottom-sheet)
add_subdirectory(drawer)
add_subdirectory(list-item)
add_subdirectory(navigation-bar)
add_subdirectory(navigation-rail)
add_subdirectory(snackbar)
add_subdirectory(tooltip)
add_subdirectory(banner)
add_subdirectory(media-card)
add_subdirectory(text-field)
add_subdirectory(text-area)
add_subdirectory(search-bar)
add_subdirectory(keyboard)
add_subdirectory(carousel)
